# Logging configuration
LOG_LEVEL: INFO
DEFAULT_LOG_DIR: "../logs"

# LLM Configuration
LLM:
  ANTHROPIC_API_KEY: null # You can set this with environment variables
  OPENAI_API_KEY: null # You can set this with environment variables
  MODEL: "gpt-4o"
  EMBEDDING_MODEL: "text-embedding-3-small"
  TEMPERATURE: 0
  MAX_TOKENS: 4095  # Max for gpt-4o

# AllegroGraph Configuration
ALLEGROGRAPH:
  REPO: "cfr2sbvr"
  CATALOG: "root"
  HOST: "localhost"
  PORT: 10035
  USER: "super"
  PASSWORD: "2002"
  HOME_DIR: "/home/adsantos/agraph-8.2.1"

# AllegroGraph Configuration
ALLEGROGRAPH_CLOUD:
  REPO: "cfr2sbvr"
  CATALOG: "root"
  HOST: "your-hostname"
  PORT: 443 
  USER: "admin"
  PASSWORD: "your-password"  # Replace with your password

# Directories and Files
DEFAULT_DATA_DIR: "../data"
DEFAULT_CHECKPOINT_DIR: "../data/checkpoints"
DEFAULT_OUTPUT_DIR: "../outputs"
DEFAULT_CHECKPOINT_FILE: null  # to be set programmatically
DEFAULT_EXTRACTION_REPORT_FILE: null  # to be set programmatically
DEFAULT_EXCEL_FILE: "../outputs/compare_items_metrics.xlsx"

# GitHub Configuration
GITHUB_REPO: "https://github.com/asantos2000/master-degree-santos-anderson.git"  # You can set this with environment variables
GITHUB_REPO_BRANCH: "master"
GITHUB_REPO_CODE_DIR: "code"

# FIBO Graph Configuration
FIBO_GRAPH: "fibo:FIBO_Graph"
FIBO_GRAPH_VECTOR_STORE: "fibo-glossary-3m-vec"

# CFR_SBVR Graph Configuration
CFR_SBVR_GRAPH: "cfr-sbvr:CFR_SBVR"
CFR_SBVR_GRAPH_VECTOR_STORE: "cfr-sbvr-3m-vec"

# Similarity search threshold for exact match
SIMILARITY_THRESHOLD: 0.99
