# Logging configuration
LOG_LEVEL: DEBUG
DEFAULT_LOG_DIR: "../logs"

# LLM Configuration
LLM:
  ANTHROPIC_API_KEY: null # You can set this with environment variables
  OPENAI_API_KEY: null # You can set this with environment variables
  MODEL: "gpt-4o"
  EMBEDDING_MODEL: "text-embedding-3-small"
  TEMPERATURE: 0
  MAX_TOKENS: 8192  # Max for gpt-4o

REFERENCE_MODELS:
  MAX_CONTEXT_LENGTH:
    gpt-4o-2024-08-06: 128_000  # GPT-4 context length
    GPT-3.5: 96_000  # Example context length for GPT-3.5
  PRICE_PER_MILLION_TOKENS:
    gpt-4o-2024-08-06: 2.50  # USD as of 2024-10-31
    GPT-3.5: 1.00  # Example price for GPT-3.5

# AllegroGraph Configuration
ALLEGROGRAPH_HOSTING: "ALLEGROGRAPH_LOCAL"  # ALLEGROGRAPH_LOCAL or ALLEGROGRAPH_CLOUD

ALLEGROGRAPH_FORCE_RUN: True # Force run the script. If set to True, the script will run regardless of risk of data loss.
ALLEGROGRAPH_CLEAN_BEFORE_RUN: True # Clean the repository before running the script.

ALLEGROGRAPH_LOCAL:
  REPO: "cfr2sbvr"
  CATALOG: "root"
  HOST: "localhost"  # ag1eawvuu0p3zv35.allegrograph.cloud for AllegroGraph cloud
  PORT: 10035  # 443 for AllegroGraph cloud
  USER: "super"  # admin for AllegroGraph cloud
  PASSWORD: "2002"  # Replace with your password
  HOME_DIR: "/home/adsantos/agraph-8.3.0"

# AllegroGraph Configuration
ALLEGROGRAPH_CLOUD:
  REPO: "cfr2sbvr"
  CATALOG: "root"
  HOST: "ag1eawvuu0p3zv35.allegrograph.cloud"
  PORT: 443 
  USER: "admin"
  PASSWORD: "GYL6N1KPB4R4xdWKIZqrYw"  # Replace with your password

# Directories and Files
DEFAULT_DATA_DIR: "../data"
DEFAULT_CHECKPOINT_DIR: "../data/checkpoints"
DEFAULT_OUTPUT_DIR: "../outputs"
DEFAULT_CHECKPOINT_FILE: null  # to be set programmatically
DEFAULT_OBJ_CACHE_FILE: null  # to be set programmatically
DEFAULT_EXTRACTION_REPORT_FILE: null  # to be set programmatically
DEFAULT_EXCEL_FILE: "../outputs/compare_items_metrics.xlsx"
DEFAULT_SCRIPTS_DIR: "../scripts"

# GitHub Configuration
GITHUB_REPO: "https://github.com/asantos2000/master-degree-santos-anderson.git"  # You can set this with environment variables
GITHUB_REPO_BRANCH: "master"
GITHUB_REPO_CODE_DIR: "code"

# FIBO Graph Configuration
FIBO_GRAPH: "fibo:FIBO_Graph"
FIBO_GRAPH_VECTOR_STORE: "fibo-glossary-3m-vec"

# CFR_SBVR Graph Configuration
CFR_SBVR_GRAPH: "cfr-sbvr:CFR_SBVR"
CFR_SBVR_GRAPH_VECTOR_STORE: "cfr-sbvr-3m-vec"

# Similarity search threshold for exact match
SIMILARITY_THRESHOLD: 0.99
