#
# FIBO
#

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cmns-av: <https://www.omg.org/spec/Commons/AnnotationVocabulary/>

SELECT DISTINCT ?class ?label ?definition ?usage_note ?explanatory_note ?description ?see_also
WHERE {
  #?class a owl:Class .
  ?class a owl:AnnotationProperty .
  #?class rdfs:label ?label .
  OPTIONAL { ?class rdfs:label ?label}
  OPTIONAL { ?class rdfs:comment ?description}
  OPTIONAL { ?class skos:definition ?definition}
  OPTIONAL { ?class rdfs:seeAlso ?see_also }
  OPTIONAL { ?class cmns-av:usageNote ?usage_note }
  OPTIONAL { ?class cmns-av:explanatoryNote ?explanatory_note }
  
  FILTER(?label = "abstract" || ?label = "source")
}
LIMIT 50

# How many definitions
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT (COUNT(?item) AS ?count)
WHERE {
  ?item skos:definition ?definition .
}

#
# CFR
#
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fro-leg-ref: <http://finregont.com/fro/ref/LegalReference.ttl#>
PREFIX fro-cfr: <http://finregont.com/fro/cfr/Code_Federal_Regulations.ttl#> 

SELECT DISTINCT ?class ?paragraph_enum_text ?paragraph_text ?divides
WHERE {
  #?class a owl:Class .
  ?class a fro-cfr:CFR_Parapraph .
  #?class rdfs:label ?label .
  OPTIONAL { ?class fro-cfr:hasParagraphEnumText ?paragraph_enum_text}
  OPTIONAL { ?class fro-cfr:hasParagraphText ?paragraph_text}
  OPTIONAL { ?class fro-leg-ref:divides ?divides}
  
  FILTER(contains(?paragraph_enum_text,"Definitions"))
}
LIMIT 50

#
# Statistics (both)
#

# How many sections and paragraphs
PREFIX fro-cfr: <http://finregont.com/fro/cfr/Code_Federal_Regulations.ttl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?type (COUNT(?item) AS ?count)
WHERE {
  ?item rdf:type ?type .
  FILTER(?type IN (fro-cfr:CFR_Parapraph, fro-cfr:CFR_Section))
}
GROUP BY ?type

# Classes
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX fro-cfr: <http://finregont.com/fro/cfr/Code_Federal_Regulations.ttl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?type (COUNT(?item) AS ?count)
WHERE {
  ?item rdf:type ?type .
  FILTER(?type IN (fro-cfr:CFR_Parapraph, fro-cfr:CFR_Section, owl:AnnotationProperty, owl:NamedIndividual, owl:AllDifferent, owl:ObjectProperty, owl:DatatypeProperty, owl:Class, owl:Restriction, skos:definition, owl:Ontology))
}
GROUP BY ?type